name: Build DarkOne

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Clone linaro toolchain
      run: |
        git clone https://github.com/archie9211/linaro -b master linaro
        git clone https://github.com/archie9211/linaro -b arm32 linaro32

        pwd
        ls
    - name: Now compiling kernel
      run: |
        export KBUILD_BUILD_USER="archie"
        export KBUILD_BUILD_HOST="Hackintosh"
        make ARCH=arm64 chef_defconfig O=out/
        make ARCH=arm64 \
                CROSS_COMPILE_ARM32=/home/runner/work/android_kernel_motorola_chef/android_kernel_motorola_chef/linaro32/bin/armv8l-linux-gnueabihf- \
                CROSS_COMPILE=/home/runner/work/android_kernel_motorola_chef/android_kernel_motorola_chef/linaro/bin/aarch64-linux-gnu- \
                -j$(nproc) O=out/ 
    - name: Make kernel zip
      run: |
        git clone https://github.com/archie9211/AnyKernel2 anykernel
        cp out/arch/arm64/boot/Image.gz-dtb anykernel
        cd anykernel
        zip -r9 DarkOne-v3.0-chef *
