name: Build DarkOne

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone kernel
      run: |
        pwd
        ls
        git clone --depth 1 --no-single-branch https://github.com/archie9211/android_kernel_motorola_chef kernel
        
    - name: Lets Do it
      run: |
        cd kernel
        TOKEN=${{secrets.TG_BOT_TOKEN}}
        CHTID=${{secrets.MY_CHAT_ID}}
        wget https://gist.githubusercontent.com/archie9211/912c1a9a9552e1a709a68383a4c2fc1f/raw/aee108778524e0f8910dfd5d612013dcc0b22bf0/build-kernel-github-actions.sh 
        chmod a+x build-kernel-github-actions.sh 
        sh build-kernel-github-actions.sh $TOKEN $CHTID
