name: Build DarkOne

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Clone linaro toolchain
      run: |
        wget -q https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
        tar  -Jxvf gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
        pwd
    - name: Now compiling kernel
      run: |
        export KBUILD_BUILD_USER="archie"
        export KBUILD_BUILD_HOST="Hackintosh"
        make ARCH=arm64 chef_defconfig O=out/
        make ARCH=arm64 CROSS_COMPILE=/home/runner/work/android_kernel_motorola_chef/android_kernel_motorola_chef/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- -j$(nproc) O=out/ 
